### PR TITLE
try updating 5.6.1 dockerfiles

### PR DESCRIPTION
**Pull request by bolliger32**
@rjleveque let's see if this works. Also bumped the anaconda image you were pulling from to python 3. Not sure if that's desirable, so feel free to switch it back python2 is preferable.

### CODE REVIEW

**Comment by bolliger32** [comment]
OK fixed the bugs. Using the continuumio image with a non-root user was causing all kinds of problems when trying to use conda from the jovyan user, so I decided to use `jupyter/base-notebook` as the base image. They're already taken care of that annoying stuff. The image is ~150MB bigger, so not a big diff. Let me know if you think thats an issue. I also caught one error in netcdf_topo where it fails (rather than skips) if xarray not installed. So I will fix that in the geoclaw repo.

**Comment by rjleveque** [comment]
@bolliger32 - Thanks for working on this.  But there seems to be a problem with using `jupyter/base-notebook` unless all you want to do is run notebooks.  When I start a container based on this, it automatically starts running the jupyter server within it and I don't seem to have access to a shell.  When I kill the server it stops the container.  But maybe I'm doing something wrong?

**Comment by bolliger32** [comment]
@rjleveque Nope not something you did wrong! I forgot to fix the command it ran. Let me know if this works. I'm still learning docker... out of curiosity what is the command you used to start up this container?

**Comment by rjleveque** [comment]
Thanks @bolliger32.  This worked fine.  I used the following commands to build:

```
docker build -t clawpack/v5.6.1_dockerimage -f Dockerfile_v5.6.1 .
docker tag clawpack/v5.6.1_dockerimage:latest  clawpack/v5.6.1_dockerimage:release
docker push clawpack/v5.6.1_dockerimage

docker build -t clawpack/v5.6.1_geoclaw -f Dockerfile_v5.6.1_geoclaw .
```
and then to run a container:
```
docker run -i -t -p 8889:8889 --name clawpack-v5.6.1_geoclaw_container clawpack/v5.6.1_geoclaw
```

I did get the following message when building, but things work ok as is I think:
```
==> WARNING: A newer version of conda exists. <==
  current version: 4.7.10
  latest version: 4.7.12

Please update conda by running

    $ conda update -n base conda
```

**Pull request merged**
